name: '6.832'
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.7.0
  - readline=7.0
  - setuptools=52.0.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - gym==0.18.3
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - numpy==1.20.3
    - pillow==8.2.0
    - pyglet==1.5.15
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - scipy==1.6.3
    - six==1.16.0
    - symengine==0.7.2
    - torch==1.8.1
    - tqdm==4.60.0
    - typing-extensions==3.10.0.0
